#goal definition
nav_msgs/Path path
geometry_msgs/PoseStamped goal
string controller_id
string goal_checker_id
string progress_checker_id
---
#result definition
std_msgs/Empty result
---
#feedback
float32 distance_to_goal
float32 speed
